export const data = [
  {
    id: 'rec34npuPIefSR9pz',
    fields: {
      Terms: 'Installments',
      'Invoice Date': '2022-04-23',
      'Customer UUID': 'rec9B4gl6UO30ZUKL',
      'Line Items': ['recnjg9yJDoItVbxO'],
      'Payment Type': 'WiPay',
      'Due Date': '2022-10-15',
      Installments: [
        'rectNxVROSqbZf7Oz',
        'rec3DnWuAAOoir1oI',
        'recqxva1fRhHDexQD',
        'recYo3wVwFbIhHsKX',
        'recn7aHUbtbnRF9z2',
      ],
      Email: 'steve@test.com',
      'Delivery Status': 'Queued',
      Notes: 'Test from Postman',
      Contact: ['recqrXoKS7Rx7PXxp'],
      'Invoice UUID': 'rec34npuPIefSR9pz',
      'Invoice Amount': 3438,
      'Total Payments': 0,
      Balance: 3438,
      'Installments Total': 3438,
      'Invoice Check': 0,
      lineItemRecords: [
        {
          Rate: 3438,
          'Invoice ID': ['rec34npuPIefSR9pz'],
          Qty: 1,
          Description: 'HYATT - 2 DOUBLE BEDS',
          'Product Type': 'package',
          'Product ID': 'CH-DB-3-5FW-2022',
          'Product UUID': 'rec0OGVY6DKoh8il4',
          Amount: 3437,
          'Line Item UUID': 'recnjg9yJDoItVbxO',
          productRecord: {
            Occupancy: 3,
            Hotel: ['CHACONIA'],
            'Per Person Package Price': 3420,
            'Room Description': [
              'Our hotel rooms offer a comfortable bed and complimentary WiFi Internet, perfect for the business or leisure traveller. For your comfort and convenience, the rooms also offer en-suite bathrooms with complimentary toiletries; air-conditioning; a flat-screen TV with cable television; a writing desk; a closet with hangers; and a mini-refrigerator.',
            ],
            'Image (from Room Code)': [
              {
                id: 'attkvjX71JO3J5OQQ',
                width: 611,
                height: 398,
                url: 'https://dl.airtable.com/.attachments/2121849d132a58a49baa362cdae83247/319a0364/Chaconia.png?ts=1652718780&userId=usr08TRuITgkMXoF9&cs=5f816327cf20f38e',
                filename: 'Chaconia.png',
                size: 1134441,
                type: 'image/png',
                thumbnails: {
                  small: {
                    url: 'https://dl.airtable.com/.attachmentThumbnails/6d0dbf2bf2219e9ff85979611bb07a04/bb9d0e4e?ts=1652718780&userId=usr08TRuITgkMXoF9&cs=ede6b17aa07be7f1',
                    width: 55,
                    height: 36,
                  },
                  large: {
                    url: 'https://dl.airtable.com/.attachmentThumbnails/240fbb5a3a1bbf4b652b018ffd886054/89b3c485?ts=1652718780&userId=usr08TRuITgkMXoF9&cs=a93a1b6fe90bebf1',
                    width: 611,
                    height: 398,
                  },
                  full: {
                    url: 'https://dl.airtable.com/.attachmentThumbnails/c1e0855e317712136a5fbd721722cbef/c2f9b95c?ts=1652718780&userId=usr08TRuITgkMXoF9&cs=dbeb022e9a710ed6',
                    width: 3000,
                    height: 3000,
                  },
                },
              },
            ],
            'Short Description': ['2 Double Beds'],
            'Check-out': ['2023-02-22'],
            'Check-in': ['2023-02-17'],
            'Number of Nights': ['5-Nights'],
          },
        },
      ],
      installmentRecords: [
        {
          Amount: 1050,
          'Due Date': '2022-06-15',
          Invoice: ['rec34npuPIefSR9pz'],
          Type: 'Installment',
          'Installment UUID': 'rec3DnWuAAOoir1oI',
        },
        {
          Amount: 386,
          'Due Date': '2022-05-15',
          Invoice: ['rec34npuPIefSR9pz'],
          Type: 'Installment',
          'Installment UUID': 'recYo3wVwFbIhHsKX',
        },
        {
          Amount: 843,
          'Due Date': '2022-07-15',
          Invoice: ['rec34npuPIefSR9pz'],
          Type: 'Installment',
          'Installment UUID': 'recn7aHUbtbnRF9z2',
        },
        {
          Amount: 1158,
          'Due Date': '2022-04-20',
          Invoice: ['rec34npuPIefSR9pz'],
          Type: '25% Deposit',
          'Installment UUID': 'rectNxVROSqbZf7Oz',
        },
      ],
    },
  },
]
